```{r map_ggplot}
library(tidyverse)
library(sf)
library(USAboundaries)

USAboundaries::us_counties(states = "California") %>% ggplot() + geom_sf()

```

```{r map_tmap}
library(tmap)

espg_CA <- 26943
epsg_wgs84 <- 4326

# creates an object with the shape of CA state (to layer in tmap)
CA_state <- USAboundaries::us_states() %>% filter(name == "California") %>%
  st_set_crs(epsg_wgs84) %>% st_transform(epsg_CA)
# creates an object with the shape of CA counties (to layer in tmap)
CA_counties <- USAboundaries::us_counties(states = "California") %>%
  st_set_crs(epsg_wgs84) %>% st_transform(espg_CA) %>% 
  select(-namelsad, -state_name, -state_abbr, -jurisdiction_type) %>% 
  mutate("county_name" = str_to_upper(name)) %>% select(-name)

# general map of CA with state border with thicker line weight than county borders
tm_shape(CA_counties) + tm_borders() + tm_shape(CA_state) + tm_borders(lwd = 2)
```

```{r sum_stats}
# county summary stats for each of data before joining to geometry

parks_asthmaCA_kids_v_adults_countystats <- parks_asthmaCA_kids_v_adults %>%
  group_by(county_name) %>% 
  mutate(county_open_park_area = sum(total_open_park_area_sqmiles), county_open_parks = sum(open_parks_tract), county_number_hospitalizations = sum(number_hospitalizations), county_avg_open_park_area = mean(total_open_park_area_sqmiles), county_avg_open_parks = mean(open_parks_tract), county_avg_hospitalizations = mean(number_hospitalizations))

parks_asthmaCA_race_ethnicity_countystats <- parks_asthmaCA_race_ethnicity %>%
  group_by(county_name) %>%
  mutate(county_open_park_area = sum(total_open_park_area_sqmiles), county_open_parks = sum(open_parks_tract), county_number_hospitalizations = sum(number_hospitalizations), county_avg_open_park_area = mean(total_open_park_area_sqmiles), county_avg_open_parks = mean(open_parks_tract), county_avg_hospitalizations = mean(number_hospitalizations))

parks_asthmaCA_kids_countystats <- parks_asthmaCA_kids %>%
  group_by(county_name) %>%
  mutate(county_open_park_area = sum(total_open_park_area_sqmiles), county_open_parks = sum(open_parks_tract), county_number_hospitalizations = sum(number_hospitalizations), county_avg_open_park_area = mean(total_open_park_area_sqmiles), county_avg_open_parks = mean(open_parks_tract), county_avg_hospitalizations = mean(number_hospitalizations))

parks_asthmaCA_kids_2_countystats <- parks_asthmaCA_kids_2 %>%
  group_by(county_name) %>%
  mutate(county_open_park_area = sum(total_open_park_area_sqmiles), county_open_parks = sum(open_parks_tract), county_number_hospitalizations = sum(number_hospitalizations), county_avg_open_park_area = mean(total_open_park_area_sqmiles), county_avg_open_parks = mean(open_parks_tract), county_avg_hospitalizations = mean(number_hospitalizations))

```


```{r join_geometry}
# this chunk joins the geometry to our data

map_kids_v_adults <- CA_counties %>% inner_join(parks_asthmaCA_kids_v_adults_countystats, by = "county_name")

map_race_ethnicity <- CA_counties %>% inner_join(parks_asthmaCA_race_ethnicity_countystats, by = "county_name")

map_kids <- CA_counties %>% inner_join(parks_asthmaCA_kids_countystats, by = "county_name")
  
map_kids2 <- CA_counties %>% inner_join(parks_asthmaCA_kids_2_countystats, by = "county_name")

```

```{r tmaps}
tm_shape(map_kids_v_adults) + tm_polygons(col = "number_hospitalizations") + tm_shape(CA_counties) + tm_borders() + tm_shape(CA_state) + tm_borders(lwd = 2)
  # need to figure out how to change the legend title for the colors


```



